<?php
/**
 * @file
 * Code for the elite_store feature.
 */

include_once 'elite_store.features.inc';


/**
 * Implements hook_node_validate().
 *
 * Part of the employee validation process, if the logged in user
 *   is a manger and has already created a store, they cannot proceed.
 *
 * @todo This may become problematic in the future as managers move stores
 *       It can be solved by changing the authorship of existing stores.
 */
function elite_store_node_validate($node, $form) {

}