<?php
/**
 * @file
 * elite_sliders.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function elite_sliders_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function elite_sliders_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function elite_sliders_node_info() {
  $items = array(
    'promo_slide' => array(
      'name' => t('Promo Slide'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
